# Generated by Django 5.1.2 on 2024-10-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleVoter', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='mean_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
